### 13. Implementation of matrix factorization

In [1]:
import numpy as np
import math
import sklearn.metrics
def matrix_factorization(R,P,Q,K,steps=5000,alpha=0.0001):
    Q=Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j]>0:
                    eij=R[i][j]-np.dot(P[i,:],Q[:,j])
                    for k in range(K):
                        P[i][k]=P[i][k]+alpha*2*eij*Q[k][j]
                        Q[k][j]=Q[k][j]+alpha*2*eij*P[i][k]
        return P,Q.T
R=[[0,5,4,2,1],[1,0,0,5,3],[1,4,4,1,0],[0,0,2,0,2],[3,1,1,0,0]]
R=np.array(R)
N=len(R)
M=len(R[0])
K=1
P=np.random.rand(N,K)
Q=np.random.rand(M,K)
nP,nQ=matrix_factorization(R,P,Q,K)
nR=np.dot(nP,nQ.T)
print(nR)
print("\nName : Dhanyatha Shree C A\nRoll No : CB.SC.I5DAS21023\n")

[[0.01610836 0.31968283 0.39444635 0.17565318 0.02258771]
 [0.03571335 0.70875927 0.87451522 0.38943542 0.05007853]
 [0.01574352 0.31244237 0.38551257 0.17167483 0.02207612]
 [0.02286717 0.45381667 0.55994977 0.24935446 0.03206515]
 [0.00689148 0.13676677 0.16875211 0.07514798 0.00966348]]

Name : Dhanyatha Shree C A
Roll No : CB.SC.I5DAS21023

